spring.application.name=LoginThymeleaf
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/login}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.sql.init.mode=always
server.port=${PORT:8080}
server.servlet.session.timeout=30m
